name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or the version you're using for your frontend

      # Navigate to the frontend directory
      - name: Navigate to frontend directory
        run: cd frontend

      # Install dependencies for the frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Build the frontend app
      - name: Build the frontend app
        run: |
          cd frontend
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch GitHub Pages uses to serve content
          folder: frontend/dist  # The folder containing your built app (inside the frontend directory)
